### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#1]
EPIC: Base Setup

As a **developer** I need  **to set up the project** so that **so it's ready to implement features**

## Acceptance Criteria:

- Acceptance Criteria 1: Django Installed
- Acceptance Criteria 2:  Project created 
- Acceptance Criteria 3: Environment variables created
- Acceptance Criteria 4: All sensitive information hidden 

## Tasks

- [x] Install Django and other dependencies
- [x] Create project
- [x] Set up env vars
- [x] Modify settings.py
