### ISSUE TITLE
Home setup and base template

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#2]
EPIC: Base Setup

As a **developer** i need to **create a home setup, a base template structure** so that  **it can be reused for other pages**

## Acceptance Criteria:

- Acceptance Criteria 1: Home app created
- Acceptance Criteria 2:  Home app templates setup
- Acceptance Criteria 3: Base templates structure created 

## Tasks

- [x] Create home app view
- [x] Create templates folders for home app including a the index.html and one in root with base.html
- [x] Set up urls home page
- [x] Modify setting.py with new app and templates directiry
