### ISSUE TITLE
Base templates

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#2]
EPIC: 

As a **developer** I need to create a **base.html page and structure** so that **it can be reused for other pages**

## Acceptance Criteria:

- Acceptance Criteria 1: Base.html and structure created
- Acceptance Criteria 2:  Navbar is included
- Acceptance Criteria 3: Footer is included

## Tasks

- [x] Create a templates folder with subfolders in root directry 
- [x] Create a base.html 
- [x] Include navbar and footer
