### ISSUE TITLE
Add toast

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#20]
EPIC: 

As a **user** i would like to receive feedback when add, edit or delete a review as well as sign up/in/out

## Acceptance Criteria:

- Acceptance Criteria 1: Toast messages are displayed when performing actions regarding reviews and sign up/in/out

## Tasks

- [x] Add toast functionality to views
- [x] Add messages in base template
- [x] modify settings.py
