### ISSUE TITLE
Add static recourses

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#4]
EPIC: Base Setup

As a **developer**, i need to **create static resources** so that **CSS, and images works on the website**

## Acceptance Criteria:

- Acceptance Criteria 1: Statics folder created
- Acceptance Criteria 2: Subfolder for CSS created
- Acceptance Criteria 3: Subfolder for Images created

## Tasks

- [ ] Create static folder in root directory
- [ ] Create subfolder for CSS
- [ ] Create subfolder for Images
