### ISSUE TITLE
Create navbar menu

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#4]
EPIC: Base Setup

As a developer I can create a navbar menu so that users easily can navigate the site on all devices

## Acceptance Criteria:

- Acceptance Criteria 1: Navbar created with links to all pages
- Acceptance Criteria 2:  Responsive on small and big screens

## Tasks

- [x]  Task 1 Create navbar
- [x]  Task 2 Add nav items and logo 
- [x] Task 3 Add styling
