### ISSUE TITLE
Create footer

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#5]
EPIC: Base Setup

As a user I can find a footer with social media links so that i can visit  the sites social media accounts.

## Acceptance Criteria:

- Acceptance Criteria 1: Footer created with social media links
- Acceptance Criteria 2: Links opens in new tab
- Acceptance Criteria 3: Links navigates correct site

## Tasks

- [x]  Task 1 Create footer 
- [x] Task 2 Add social media icons 
- [x] Task 3 Style footer
