### ISSUE TITLE
Styling Allauth pages

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#7]
EPIC: Authentication

As a website owner I want to have the Allauth pages customized so that the style matches the rest of the site

## Acceptance Criteria:

- Acceptance Criteria 1: Sign up page have custom styling
- Acceptance Criteria 2: Sign in page have custom styling 
- Acceptance Criteria 3: Sign out page have custom styling

## Tasks

- [x]  Copy the allauth account templates into templates folder
- [x] Customize styling to the sign up page
- [x]  Customize styling to the sign in page
- [x] Customize styling to the sign out page
