### ISSUE TITLE
Add Car a review 

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#8]
EPIC: Reviews

As a **user** i can **add a car review** so that **i can share it for other users to read**

## Acceptance Criteria:

- Acceptance Criteria 1: Users can access a form to input their car reviews.
- Acceptance Criteria 2: Users can submit the form, and the review is saved.
- Acceptance Criteria 3: Submitted reviews are visible on the website.

## Tasks

- [x] Create a review app
- [x] Create a model representing the car review
- [x] Create a templates folder in reviews app and add the html pages
- [x] Create a form for Car review
- [x]  Create a view to Add car review
