### ISSUE TITLE
Listview Reviews

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Carrevs-Car-Reviews#9]
EPIC: Reviews

As a **user** I can  **view all users reviews** so that **I can read them**

## Acceptance Criteria:

- Acceptance Criteria 1: User can view all reviews on a page

## Tasks

- [x] Create a class listview 
- [x] Create a html page to view all reviews
- [x] Style the page
